kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configmap
  namespace: moaproject
data:
  nginx.conf: |-
    user    nginx;
    error_log   /var/log/nginx/error-http.log;
    pid         /var/run/nginx.pid;

    worker_processes  auto;
    worker_rlimit_nofile 17384;

    events {
        worker_connections  30000;  ## Default: 1024
        multi_accept on;
        use epoll;
    }

    http {
      access_log on;
      access_log    /var/log/nginx/access.log;
    
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      client_max_body_size 6024M;
      proxy_request_buffering off;
    
      map $http_upgrade $connection_upgrade {
          default upgrade;
          ''      close;
      }
    
      server {
          listen 80;
    
          location / {
              proxy_pass http://moa-client-service;
              proxy_http_version 2.0;
              proxy_set_header X-Real-IP $proxy_protocol_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_set_header X-Nginx-Proxy true;
          }
    
          location /api {
              proxy_pass http://moa-api-service;
              proxy_http_version 2.0;
              proxy_set_header X-Real-IP $proxy_protocol_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_set_header X-Nginx-Proxy true;
          }
      }
    }